# Etapa 1: Build
FROM maven:3.9.6-eclipse-temurin-21 AS builder
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Etapa 2: Runtime
FROM eclipse-temurin:21-jdk
WORKDIR /app
COPY target/producto-service-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080 8081 8082
ENTRYPOINT ["java", "-jar", "app.jar"]
